// backend/utils/contractGenerator.js
import PDFDocument from "pdfkit";
import { Readable } from "stream";

export const generateLicenseContract = async ({
  buyerName,
  buyerEmail,
  sellerName,
  beatTitle,
  licenseType,
  licenseDetails,
  amountPaid,
  transactionId,
  orderId,
  purchaseDate
}) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on("data", chunk => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fontSize(20).font("Helvetica-Bold").text("DHUUN", { align: "center" });
    doc.fontSize(14).font("Helvetica").text("Beat License Agreement", { align: "center" });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Order info
    doc.fontSize(10).font("Helvetica");
    doc.text(`Order ID: ${orderId}`);
    doc.text(`Date: ${new Date(purchaseDate).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
    doc.text(`Transaction ID: ${transactionId}`);
    doc.moveDown();

    // Parties
    doc.fontSize(12).font("Helvetica-Bold").text("PARTIES");
    doc.fontSize(10).font("Helvetica");
    doc.text(`Licensor (Seller): ${sellerName}`);
    doc.text(`Licensee (Buyer): ${buyerName} <${buyerEmail}>`);
    doc.moveDown();

    // Beat info
    doc.fontSize(12).font("Helvetica-Bold").text("BEAT DETAILS");
    doc.fontSize(10).font("Helvetica");
    doc.text(`Beat Title: ${beatTitle}`);
    doc.text(`License Type: ${licenseType.toUpperCase()}`);
    doc.text(`Amount Paid: Rs ${amountPaid}`);
    doc.moveDown();

    // Rights granted
    doc.fontSize(12).font("Helvetica-Bold").text("RIGHTS GRANTED");
    doc.fontSize(10).font("Helvetica");
    doc.text(`Commercial Use: ${licenseDetails.commercialUse ? "Yes" : "No"}`);
    doc.text(`Exclusive Rights: ${licenseDetails.isExclusive ? "Yes — beat retired from marketplace" : "No"}`);
    doc.text(`Stream Limit: ${licenseDetails.streamLimit}`);
    doc.text(`Distribution Copies: ${licenseDetails.distributionLimit ?? "Unlimited"}`);
    doc.text(`File Formats: ${licenseDetails.fileFormats.join(", ")}`);
    doc.text(`Producer Credit Required: ${licenseDetails.creditRequired ? "Yes" : "No"}`);
    doc.moveDown();

    // Terms
    doc.fontSize(12).font("Helvetica-Bold").text("TERMS");
    doc.fontSize(9).font("Helvetica");
    doc.text(
      "This agreement is governed by the laws of Nepal. The Licensee may use the beat " +
      "solely within the scope of rights granted above. Any use beyond the stated limits " +
      "requires a new license agreement. Dhuun acts as the marketplace facilitator and " +
      "is not a party to disputes between Licensor and Licensee.",
      { align: "justify" }
    );
    doc.moveDown();

    // Signature line
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);
    doc.fontSize(9).text("Auto-generated by Dhuun · dhuun-psi.vercel.app", { align: "center" });

    doc.end();
  });
};